name: emailer
channels:
- defaults
- conda-forge
dependencies:
- backcall=0.1.0
- ca-certificates=2018.03.07
- certifi=2018.4.16
- decorator=4.3.0
- entrypoints=0.2.3
- intel-openmp=2018.0.0
- ipython=6.4.0
- ipython_genutils=0.2.0
- jedi=0.12.0
- keyring=12.0.1
- libedit=3.1.20170329
- libffi=3.2.1
- mkl=2018.0.2
- mkl_fft=1.0.1
- mkl_random=1.0.1
- ncurses=6.1
- numpy=1.14.2
- openssl=1.0.2o
- pandas=0.23.0
- parso=0.2.0
- pexpect=4.5.0
- pickleshare=0.7.4
- pip=10.0.1
- prompt_toolkit=1.0.15
- ptyprocess=0.5.2
- pygments=2.2.0
- python=3.6.5
- python-dateutil=2.7.3
- pytz=2018.4
- readline=7.0
- setuptools=39.1.0
- simplegeneric=0.8.1
- six=1.11.0
- sqlite=3.23.1
- tk=8.6.7
- traitlets=4.3.2
- wcwidth=0.1.7
- wheel=0.31.1
- xlrd=1.1.0
- xz=5.2.4
- zlib=1.2.11
- pip:
  - asn1crypto==0.24.0
  - cffi==1.11.5
  - cryptography==2.2.2
  - idna==2.6
  - ipython-genutils==0.2.0
  - jeepney==0.3.1
  - mkl-fft==1.0.0
  - mkl-random==1.0.1
  - prompt-toolkit==1.0.15
  - pycparser==2.18
  - secretstorage==3.0.1
  - yagmail==0.10.212

